//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveMe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.UsersLeaveApply = new HashSet<UsersLeaveApply>();
            this.UsersLeaveApply1 = new HashSet<UsersLeaveApply>();
            this.UsersEducation = new HashSet<UsersEducation>();
            this.UsersDocuments = new HashSet<UsersDocuments>();
            this.UsersEmergencyContact = new HashSet<UsersEmergencyContact>();
            this.UsersExperience = new HashSet<UsersExperience>();
            this.UsersProfile = new HashSet<UsersProfile>();
            this.UsersReporting = new HashSet<UsersReporting>();
            this.UsersReporting1 = new HashSet<UsersReporting>();
            this.UsersRole = new HashSet<UsersRole>();
            this.UsersWork = new HashSet<UsersWork>();
        }
    
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTerminated { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<UsersLeaveApply> UsersLeaveApply { get; set; }
        public virtual ICollection<UsersLeaveApply> UsersLeaveApply1 { get; set; }
        public virtual ICollection<UsersEducation> UsersEducation { get; set; }
        public virtual ICollection<UsersDocuments> UsersDocuments { get; set; }
        public virtual ICollection<UsersEmergencyContact> UsersEmergencyContact { get; set; }
        public virtual ICollection<UsersExperience> UsersExperience { get; set; }
        public virtual ICollection<UsersProfile> UsersProfile { get; set; }
        public virtual ICollection<UsersReporting> UsersReporting { get; set; }
        public virtual ICollection<UsersReporting> UsersReporting1 { get; set; }
        public virtual ICollection<UsersRole> UsersRole { get; set; }
        public virtual ICollection<UsersWork> UsersWork { get; set; }
    }
}
