//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveMe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLeaveApply
    {
        public int Id { get; set; }
        public System.Guid UserID { get; set; }
        public int LeaveTypeID { get; set; }
        public System.DateTime LeaveFromDate { get; set; }
        public System.DateTime LeaveToDate { get; set; }
        public Nullable<int> ApprovedDays { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Reason { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
