CREATE TABLE [dbo].[UsersRole]
(
	[ID] INT NOT NULL IDENTITY PRIMARY KEY,
	[UserID] UNIQUEIDENTIFIER NOT NULL , 
	[RoleID] INT NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL, 
	[UpdatedBy] UNIQUEIDENTIFIER NULL, 
	[CreatedDate] DATETIME NOT NULL DEFAULT (getdate()) , 
	[UpdatedDate] DATETIME NULL, 
	CONSTRAINT [FK_UserRole_ToUser] FOREIGN KEY ([UserID]) REFERENCES [Users]([UserID]), 
	CONSTRAINT [FK_UserRole_ToRole] FOREIGN KEY ([RoleID]) REFERENCES [Roles]([RoleID]) 
)
