CREATE TABLE [dbo].[UsersWork]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserID] UNIQUEIDENTIFIER NOT NULL,
	[WorkTitle] NVARCHAR (150) NOT NULL,
	[JoinDate] DATETIME NOT NULL,
	[Loction] NVARCHAR(150) NOT NULL,
	[IsActive] BIT NULL DEFAULT 0, 
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL, 
	[UpdatedBy] UNIQUEIDENTIFIER NULL, 
	[CreatedDate] DATETIME NOT NULL , 
	[UpdatedDate] DATETIME NULL, 
	CONSTRAINT [FK_RoleName_ToUser] UNIQUE (WorkTitle),
	CONSTRAINT [FK_UserWork_ToUser] FOREIGN KEY ([UserID]) REFERENCES [Users]([UserID]), 
)
